"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowLeft, ArrowRight, Award, BadgeCheck, BookOpen, CheckCircle2, Dumbbell, Target, TimerReset, TrendingUp, UsersRound } from "lucide-react";
import type { TrainerProfile } from "./trainer-data";
import { outlineButton, primaryButton, reveal, shell } from "./trainers-shared";

const approach = [
  [Target, "Assess", "We assess your current fitness level, goals and movement patterns."],
  [BookOpen, "Plan", "A customized training plan designed specifically for your goals."],
  [Dumbbell, "Train", "Smart training with progressive overload and strong technique."],
  [TrendingUp, "Achieve", "Track progress, stay consistent and achieve results that last."],
] as const;

export default function TrainerDetailPage({ trainer }: { trainer: TrainerProfile }) {
  const firstName = trainer.name.split(" ")[0];
  const bookingHref = `/book-session?trainer=${encodeURIComponent(trainer.slug)}`;

  return <>
    <section className="relative min-h-[660px] overflow-hidden border-b border-bazooka-border/70 bg-cover bg-center" style={{backgroundImage:`url(${trainer.image})`}}><div className="absolute inset-0 bg-gradient-to-r from-black via-black/78 to-black/18"/><div className="absolute inset-0 bg-gradient-to-t from-black/68 via-transparent to-black/18"/><div className={`${shell} relative z-10 flex min-h-[660px] items-center py-14`}><motion.div {...reveal} className="max-w-[610px]"><Link href="/trainers" className="mb-7 inline-flex items-center gap-2 text-[9px] font-black uppercase text-bazooka-text-secondary transition-all hover:-translate-x-0.5 hover:text-bazooka-lime"><ArrowLeft className="size-3.5"/>Back To Trainers</Link><span className="block text-[10px] font-black uppercase text-bazooka-lime">{trainer.role}</span><h1 className="font-display mt-3 break-words text-[50px] font-black uppercase leading-[.88] min-[380px]:text-[58px] sm:text-[72px] lg:text-[84px]">{trainer.name}</h1><p className="mt-5 max-w-[500px] text-[12px] leading-6 text-bazooka-text-secondary">{trainer.summary}</p><div className="mt-5 grid max-w-[430px] gap-2 text-[9px] text-bazooka-text-secondary sm:grid-cols-2"><span className="flex items-center gap-2"><TimerReset className="size-4 text-bazooka-lime"/>{trainer.experience} Experience</span><span className="flex items-center gap-2"><Award className="size-4 text-bazooka-lime"/>{trainer.certification}</span><span className="flex items-center gap-2"><UsersRound className="size-4 text-bazooka-lime"/>500+ Transformations</span><span className="flex items-center gap-2"><Dumbbell className="size-4 text-bazooka-lime"/>{trainer.specialties[0]}</span></div><div className="mt-7 grid gap-3 sm:flex sm:flex-wrap"><Link href={bookingHref} className={`${primaryButton} w-full sm:w-auto`}>Book A Session <ArrowRight className="size-4 transition-transform group-hover:translate-x-1"/></Link><Link href="/trainers" className={`${outlineButton} w-full sm:w-auto`}>View All Trainers <ArrowRight className="size-4 transition-transform group-hover:translate-x-1"/></Link></div></motion.div></div><div className="absolute bottom-8 right-[7%] hidden max-w-[260px] rounded-[6px] border border-white/10 bg-black/58 p-5 backdrop-blur-sm xl:block"><span className="font-display text-[42px] leading-none text-bazooka-lime">“</span><p className="mt-2 text-[11px] leading-5 text-white">{trainer.quote}</p><span className="font-display mt-4 block text-[13px] italic text-bazooka-lime">— {trainer.name}</span></div></section>

    <section className="border-b border-bazooka-border/70 bg-bazooka-black py-6"><div className={`${shell} grid gap-4 rounded-[5px] border border-bazooka-border-strong bg-bazooka-surface px-5 py-5 sm:grid-cols-2 lg:grid-cols-6`}>{[["12+","Years Experience"],["50+","Specializations"],["500+","Transformations"],["10+","Certifications"],["1000+","Happy Members"],["98%","Success Rate"]].map(([value,label])=><div key={label} className="rounded-[4px] border border-transparent py-2 text-center transition-all duration-300 hover:border-bazooka-lime/30 hover:bg-bazooka-lime/5"><strong className="font-display text-[24px] font-black">{value}</strong><span className="mt-1 block text-[8px] uppercase text-bazooka-text-secondary">{label}</span></div>)}</div></section>

    <section className="border-b border-bazooka-border/70 bg-bazooka-soft-black py-14 md:py-16"><div className={`${shell} grid gap-4 lg:grid-cols-[.9fr_.9fr_.7fr]`}><motion.article {...reveal} className="rounded-[6px] border border-bazooka-border-strong bg-bazooka-surface p-6"><h2 className="font-display text-[28px] font-black uppercase">About <span className="text-bazooka-lime">{firstName}</span></h2><p className="mt-4 text-[10px] leading-5 text-bazooka-text-secondary">With {trainer.experience.toLowerCase()} of experience, {firstName} has helped members improve strength, performance and confidence through structured coaching and consistent progress.</p><p className="mt-4 text-[10px] leading-5 text-bazooka-text-secondary">The approach is simple: proper technique, focused effort, smart progression and a mindset built for long-term results.</p></motion.article><motion.div {...reveal} className="group min-h-[340px] overflow-hidden rounded-[6px] border border-bazooka-border-strong bg-cover bg-center transition-all duration-500 hover:border-bazooka-lime" style={{backgroundImage:`url(${trainer.secondaryImage})`}}/><motion.article {...reveal} className="rounded-[6px] border border-bazooka-border-strong bg-bazooka-surface p-6"><h3 className="font-display text-[25px] font-black uppercase text-bazooka-lime">Expertise</h3><div className="mt-5 space-y-3">{trainer.expertise.map(item=><p key={item} className="flex items-center gap-3 text-[10px] text-bazooka-text-secondary"><CheckCircle2 className="size-4 text-bazooka-lime"/>{item}</p>)}</div></motion.article></div></section>

    <section className="border-b border-bazooka-border/70 bg-bazooka-black py-14 md:py-16"><div className={`${shell} grid gap-4 lg:grid-cols-[1fr_1fr_.9fr]`}><motion.article {...reveal} className="rounded-[6px] border border-bazooka-border-strong bg-bazooka-surface p-6"><h3 className="font-display text-[24px] font-black uppercase text-bazooka-lime">Certifications</h3><div className="mt-5 space-y-3">{trainer.certifications.map(item=><p key={item} className="flex items-start gap-3 text-[10px] text-bazooka-text-secondary"><BadgeCheck className="mt-0.5 size-4 shrink-0 text-bazooka-lime"/>{item}</p>)}</div></motion.article><motion.article {...reveal} className="rounded-[6px] border border-bazooka-border-strong bg-bazooka-surface p-6"><h3 className="font-display text-[24px] font-black uppercase text-bazooka-lime">Education</h3><div className="mt-5 space-y-3">{trainer.education.map(item=><p key={item} className="flex items-start gap-3 text-[10px] text-bazooka-text-secondary"><Award className="mt-0.5 size-4 shrink-0 text-bazooka-lime"/>{item}</p>)}</div></motion.article><motion.div {...reveal} className="relative min-h-[310px] overflow-hidden rounded-[6px] border border-bazooka-border-strong bg-cover bg-center" style={{backgroundImage:`url(${trainer.image})`}}><div className="absolute inset-0 bg-gradient-to-t from-black/50 via-black/10 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-6"><span className="text-[9px] font-black uppercase text-bazooka-lime">Coach Profile</span><p className="font-display mt-1 text-[22px] font-black uppercase text-white">Train With {firstName}</p></div></motion.div></div></section>

    <section className="border-b border-bazooka-border/70 bg-bazooka-soft-black py-14 md:py-16"><div className={shell}><motion.div {...reveal} className="overflow-hidden rounded-[6px] border border-bazooka-border-strong bg-bazooka-surface"><div className="p-6"><h2 className="font-display text-[30px] font-black uppercase">{firstName}’s Training Approach</h2></div><div className="grid md:grid-cols-2 xl:grid-cols-4">{approach.map(([Icon,title,text])=><div key={title} className="group border-t border-bazooka-border p-6 transition-colors duration-300 hover:bg-bazooka-lime/5 xl:border-r"><Icon className="size-6 text-bazooka-lime transition-transform duration-300 group-hover:scale-110"/><h3 className="font-display mt-4 text-[18px] font-black uppercase">{title}</h3><p className="mt-2 text-[9px] leading-4 text-bazooka-text-secondary">{text}</p></div>)}</div></motion.div></div></section>

    <section className="border-b border-bazooka-border/70 bg-bazooka-black py-10"><div className={shell}><motion.div {...reveal} className="group relative overflow-hidden rounded-[6px] border border-bazooka-border-strong bg-cover bg-center px-6 py-10 transition-all duration-500 hover:border-bazooka-lime/60 sm:px-9" style={{backgroundImage:`url(${trainer.secondaryImage})`}}><div className="absolute inset-0 bg-gradient-to-r from-black via-black/84 to-black/22"/><div className="relative z-10 flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="font-display text-[34px] font-black uppercase leading-[.95]">Train With {firstName} & <span className="text-bazooka-lime">Transform Yourself</span></h2><p className="mt-2 text-[10px] text-bazooka-text-secondary">Book your session today and take the first step towards a stronger you.</p></div><div className="grid gap-3 sm:flex sm:flex-wrap"><Link href={bookingHref} className={`${primaryButton} w-full sm:w-auto`}>Book A Session <ArrowRight className="size-4 transition-transform group-hover:translate-x-1"/></Link><Link href="/memberships" className={`${outlineButton} w-full sm:w-auto`}>View Memberships <ArrowRight className="size-4"/></Link></div></div></motion.div></div></section>
  </>;
}
