import Link from "next/link";
import { AlertCircle, ArrowRight, Banknote, CalendarDays, CheckCircle2, Clock3, CreditCard, Dumbbell, Handshake, Headphones, Mail, MapPin, Package, Phone, ShieldCheck, Snowflake, UserRound, UsersRound, XCircle } from "lucide-react";

export type PolicyKind = "membership" | "cancellation" | "refund";
type Card = { title: string; text: string; bullets?: string[]; icon: typeof UserRound };

const data: Record<PolicyKind,{crumb:string;title:string;accent:string;intro:string;section:string;cards:Card[];notes:string[]}> = {
 membership:{crumb:"Membership Terms",title:"MEMBERSHIP",accent:"TERMS & CONDITIONS",intro:"Please read these terms carefully before becoming a part of the Bazooka Fitness community.",section:"Membership Terms & Conditions",cards:[
  {icon:UserRound,title:"Membership Eligibility",text:"Membership is open to individuals above 16 years of age. Members below 18 must have a parent or guardian’s consent."},{icon:CalendarDays,title:"Membership Types & Duration",text:"Bazooka offers various membership plans with different durations. The duration begins from the date of activation."},{icon:CreditCard,title:"Payment Policy",text:"Full payment must be completed to activate the membership. All fees are non-refundable and non-transferable."},{icon:Snowflake,title:"Membership Freeze",text:"Membership can be frozen for genuine medical or personal reasons for a maximum of 15 days in a year with valid proof."},{icon:XCircle,title:"Cancellation Policy",text:"Membership once purchased cannot be cancelled or refunded. In case of genuine issues, management’s decision is final."},{icon:CheckCircle2,title:"Attendance & Access",text:"Members must check-in using their authorized access. Tailgating or sharing access is strictly prohibited."},{icon:Dumbbell,title:"Gym Etiquette",text:"Members must maintain hygiene, respect others, and follow gym rules. Appropriate workout attire and clean shoes are mandatory."},{icon:Package,title:"Personal Belongings",text:"Bazooka is not responsible for loss or damage of personal belongings. Use lockers provided during your workout."},{icon:UserRound,title:"Trainer Guidance",text:"Always consult with trainers before starting any new program. Follow instructions to avoid injuries and ensure safety."},{icon:ShieldCheck,title:"Health & Liability",text:"Members must disclose relevant medical conditions. Bazooka is not liable for injury due to negligence or misconduct."},{icon:Dumbbell,title:"Facilities & Equipment",text:"Use all equipment and facilities at the member’s own risk. Please handle equipment with care."},{icon:Handshake,title:"Code of Conduct",text:"Misconduct, harassment, or violation of rules may result in suspension or termination of membership."}],notes:["Timings and facilities are subject to change without prior notice.","Bazooka reserves the right to amend these terms and conditions at any time.","By purchasing a membership, you agree to abide by all the terms and policies of Bazooka Fitness."]},
 cancellation:{crumb:"Cancellation Policy",title:"CANCELLATION",accent:"POLICY",intro:"We believe in transparency and fairness. Please read our cancellation policy carefully.",section:"Our Cancellation Policy",cards:[
  {icon:CalendarDays,title:"Membership Cancellation",text:"Members may cancel their membership by submitting a written request at the front desk or via email.",bullets:["Cancellation will be effective from the end of the current billing cycle."]},{icon:Clock3,title:"Notice Period",text:"A minimum notice period of 30 days is required before cancellation.",bullets:["Membership will remain active until the end of the notice period."]},{icon:CreditCard,title:"Refund Policy",text:"Membership fees are non-refundable under ordinary circumstances.",bullets:["No refunds for partial months or unused days."]},{icon:Snowflake,title:"Membership Freeze",text:"Instead of cancellation, you may freeze your membership.",bullets:["Minimum freeze duration: 15 days","Maximum freeze duration: 60 days in a year"]},{icon:Clock3,title:"Package / Service Cancellation",text:"For PT sessions, nutrition plans, or other add-on services:",bullets:["24 hours notice is required for cancellation or rescheduling."]},{icon:AlertCircle,title:"Late Payments",text:"If membership payments are not made on time, Bazooka Fitness reserves the right to:",bullets:["Suspend access until the payment is cleared."]}],notes:["Bazooka Fitness reserves the right to modify this cancellation policy at any time without prior notice.","Any changes will be updated on our website and communicated at the gym where appropriate."]},
 refund:{crumb:"Refund Policy",title:"REFUND",accent:"POLICY",intro:"At Bazooka Fitness, we are committed to complete transparency and fairness in every transaction. Please read our refund policy carefully.",section:"Our Refund Policy",cards:[
  {icon:CalendarDays,title:"Membership Fees",text:"Membership fees are non-refundable once the membership has been activated.",bullets:["No refunds for change of mind.","Membership can be frozen as per freeze policy."]},{icon:UserRound,title:"Free Trial",text:"If you are not satisfied with your free trial experience, please inform us during your trial period.",bullets:["No charges will be applied if you do not continue with a paid plan."]},{icon:CalendarDays,title:"Cancellation Before Activation",text:"If you cancel your membership before activation, you are eligible for a full refund.",bullets:["Eligible refunds are processed within 7–10 working days."]},{icon:Package,title:"Package & Add-on Services",text:"Fees paid for add-on services, personal training, nutrition plans, or workshops are non-refundable.",bullets:["You may reschedule the service subject to availability."]},{icon:Snowflake,title:"Membership Freeze",text:"We do not offer refunds for days not utilized before freezing.",bullets:["You may freeze your membership as per the terms and conditions."]},{icon:Banknote,title:"Refund Process",text:"Eligible refunds will be initiated to the original mode of payment.",bullets:["Refunds will be processed within 7–10 working days after approval."]}],notes:["Refunds will be considered only in cases that fall under our Refund Policy.","Bazooka Fitness reserves the right to approve or decline any refund request.","This policy is subject to change; material updates will be reflected on this page."]}
};
const features=[[ShieldCheck,"Transparent","Clear policies with no hidden terms."],[Handshake,"Fair & Honest","We treat every member fairly."],[Clock3,"Timely Support","Our team is here to help."],[UsersRound,"Member First","Your fitness journey matters."]] as const;
const shell="mx-auto w-full max-w-[1440px] px-5 sm:px-8 lg:px-12";

export default function PolicyPage({kind}:{kind:PolicyKind}){const p=data[kind];return <main className="min-h-screen bg-bazooka-black text-bazooka-text">
 <section className="relative min-h-[430px] overflow-hidden border-b border-bazooka-border/70 bg-[url('https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1800&q=90')] bg-cover bg-center"><div className="absolute inset-0 bg-gradient-to-r from-black via-black/88 to-black/25"/><div className={`${shell} relative z-10 flex min-h-[430px] items-center py-12`}><div className="max-w-[650px]"><p className="text-[10px] text-bazooka-text-secondary">Home <span className="mx-2 text-bazooka-lime">›</span> {p.crumb}</p><h1 className="font-display mt-7 text-[50px] font-black uppercase leading-[.9] sm:text-[68px]">{p.title}<br/><span className="text-bazooka-lime">{p.accent}</span></h1><span className="mt-6 block h-0.5 w-10 bg-bazooka-lime"/><p className="mt-5 max-w-[510px] text-[12px] leading-6 text-bazooka-text-secondary">{p.intro}</p></div></div></section>
 <section className="bg-bazooka-soft-black py-7"><div className={shell}><div className="grid rounded-[6px] border border-bazooka-border-strong bg-bazooka-surface sm:grid-cols-2 lg:grid-cols-4">{features.map(([Icon,a,b])=><div key={a} className="flex min-h-[110px] items-center gap-4 border-b border-bazooka-border p-5 last:border-0 sm:border-r lg:border-b-0"><Icon className="size-8 shrink-0 text-bazooka-lime"/><div><h2 className="font-display text-[16px] font-black uppercase">{a}</h2><p className="mt-1 text-[9px] leading-4 text-bazooka-text-secondary">{b}</p></div></div>)}</div></div></section>
 <section className="bg-bazooka-black py-8"><div className={shell}><div className="rounded-[6px] border border-bazooka-border-strong bg-bazooka-surface p-5 sm:p-7"><h2 className="font-display text-[30px] font-black uppercase">{p.section.split(" ").slice(0,1)} <span className="text-bazooka-lime">{p.section.split(" ").slice(1).join(" ")}</span></h2><div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{p.cards.map((c,i)=><article key={c.title} className="min-h-[210px] rounded-[5px] border border-bazooka-border-strong bg-bazooka-black p-5"><div className="flex items-center gap-3"><c.icon className="size-8 text-bazooka-lime"/><span className="font-display text-[20px] font-black text-bazooka-lime">{String(i+1).padStart(2,"0")}.</span><h3 className="font-display text-[16px] font-black uppercase">{c.title}</h3></div><p className="mt-4 text-[10px] leading-5 text-bazooka-text-secondary">{c.text}</p>{c.bullets?.map(x=><p key={x} className="mt-3 flex gap-2 text-[9px] leading-5 text-bazooka-text-secondary"><ArrowRight className="mt-1 size-3 shrink-0 text-bazooka-lime"/>{x}</p>)}</article>)}</div></div>
 <div className="relative mt-4 overflow-hidden rounded-[6px] border border-bazooka-border-strong bg-bazooka-surface p-6"><div className="flex gap-5"><AlertCircle className="size-10 shrink-0 text-bazooka-lime"/><div><h2 className="font-display text-[18px] font-black uppercase text-bazooka-lime">Important Notes</h2>{p.notes.map(n=><p key={n} className="mt-2 text-[9px] leading-4 text-bazooka-text-secondary">• {n}</p>)}</div></div></div>
 <div className="mt-4 grid items-center gap-5 rounded-[6px] border border-bazooka-lime/70 bg-bazooka-surface p-6 lg:grid-cols-[1fr_auto_auto_auto_auto]"><div className="flex gap-4"><Headphones className="size-10 text-bazooka-lime"/><div><h2 className="font-display text-[22px] font-black uppercase">Need Help?</h2><p className="text-[9px] text-bazooka-text-secondary">Our team is here to assist you with policy or membership queries.</p></div></div><div className="text-[9px]"><MapPin className="mb-2 size-4 text-bazooka-lime"/><b>Visit Us</b><p className="mt-1 text-bazooka-text-secondary">Sardarpura, Jodhpur</p></div><div className="text-[9px]"><Phone className="mb-2 size-4 text-bazooka-lime"/><b>Call Us</b><p className="mt-1 text-bazooka-text-secondary">+91 91164 05151</p></div><div className="text-[9px]"><Mail className="mb-2 size-4 text-bazooka-lime"/><b>Email Us</b><p className="mt-1 text-bazooka-text-secondary">info@bazooka.fit</p></div><Link href="/contact" className="inline-flex h-10 items-center justify-center gap-2 rounded-[4px] bg-bazooka-lime px-5 text-[9px] font-black uppercase text-black transition hover:bg-bazooka-lime-hover">Contact Us <ArrowRight className="size-4"/></Link></div>
 </div></section>
 </main>}
