"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowRight, Clock3, Coffee, GlassWater, MapPin, Sandwich, Sparkles, UtensilsCrossed } from "lucide-react";

const shell = "mx-auto w-[min(calc(100%-32px),1180px)] sm:w-[min(calc(100%-40px),1180px)] md:w-[min(calc(100%-64px),1180px)]";
const reveal = { initial: { opacity: 0, y: 24 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: 0.08 }, transition: { duration: 0.55, ease: "easeOut" as const } };

const categories = [
  [Sandwich, "Meals & Snacks", "Ask the Cafe Bazooka team about the food and snack options available today."],
  [GlassWater, "Drinks & Shakes", "Check the current drinks and shake selection during your visit."],
  [Sparkles, "Light Options", "Lighter food options may be available depending on the day and current menu."],
  [Coffee, "Coffee & Refreshments", "Coffee and other refreshments are part of the cafe selection when available."],
] as const;

const benefits = [
  [UtensilsCrossed, "Inside Bazooka Fitness", "Visit the cafe without leaving the club during your Bazooka Fitness experience."],
  [GlassWater, "Food & Drinks", "Choose from the food, drinks and refreshments currently available at the cafe."],
  [Sparkles, "Easy Stop During Your Visit", "Train, take a break and stop by the cafe from the same location."],
] as const;

const gallery = [
  "https://images.unsplash.com/photo-1543362906-acfc16c67564?auto=format&fit=crop&w=1200&q=88",
  "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=88",
  "https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?auto=format&fit=crop&w=1200&q=88",
];

export default function CafeBazookaPage() {
  return <main className="min-h-screen overflow-x-hidden bg-bazooka-black text-bazooka-text">
    <section className="relative min-h-[620px] overflow-hidden border-b border-bazooka-border/70 sm:min-h-[680px]">
      <div className="absolute inset-0 bg-[url('https://images.unsplash.com/photo-1543362906-acfc16c67564?auto=format&fit=crop&w=1800&q=90')] bg-cover bg-center" />
      <div className="absolute inset-0 bg-gradient-to-r from-black via-black/80 to-black/25" /><div className="absolute inset-0 bg-gradient-to-t from-bazooka-black via-transparent to-black/20" />
      <div className={`${shell} relative z-10 flex min-h-[620px] items-end pb-12 pt-32 sm:min-h-[680px] sm:pb-16 lg:items-center lg:pb-0`}>
        <motion.div {...reveal} className="max-w-[760px]">
          <span className="inline-flex items-center gap-2 rounded-full border border-bazooka-lime/40 bg-black/45 px-3.5 py-2 text-[8px] font-black uppercase tracking-[.1em] text-bazooka-lime backdrop-blur-sm sm:px-4 sm:text-[9px]"><UtensilsCrossed className="size-4"/> Inside Bazooka Fitness</span>
          <h1 className="font-display mt-5 max-w-full text-[48px] font-black uppercase leading-[.84] tracking-[-1.5px] min-[380px]:text-[54px] sm:text-[74px] md:text-[88px]">Cafe <span className="text-bazooka-lime">Bazooka.</span></h1>
          <p className="mt-5 max-w-[620px] text-[11px] leading-6 text-bazooka-text-secondary sm:text-[13px]">Cafe Bazooka brings food, drinks and refreshments into the Bazooka Fitness experience. Stop by during your visit and check what is available that day.</p>
          <div className="mt-7 grid gap-3 sm:flex sm:flex-wrap"><a href="#menu" className="inline-flex h-11 w-full items-center justify-center gap-3 rounded-[4px] bg-bazooka-lime px-6 text-[10px] font-black uppercase text-black transition hover:bg-bazooka-lime-hover active:scale-[.98] sm:w-auto">Explore The Cafe <ArrowRight className="size-4"/></a><Link href="/contact" className="inline-flex h-11 w-full items-center justify-center gap-3 rounded-[4px] border border-white/20 bg-black/45 px-6 text-[10px] font-black uppercase text-white backdrop-blur-sm transition hover:border-bazooka-lime hover:text-bazooka-lime active:scale-[.98] sm:w-auto">Contact Bazooka</Link></div>
        </motion.div>
      </div>
    </section>

    <section className="border-b border-bazooka-border/70 bg-bazooka-soft-black py-14 sm:py-16 md:py-20"><div className={`${shell} grid gap-9 lg:grid-cols-[.9fr_1.1fr] lg:items-center`}><motion.div {...reveal}><span className="text-[9px] font-black uppercase tracking-[.12em] text-bazooka-lime">Part Of The Club Experience</span><h2 className="font-display mt-3 text-[36px] font-black uppercase leading-[.9] min-[380px]:text-[40px] sm:text-[52px]">Train. Take A Break.<br/>Visit The Cafe.</h2><p className="mt-5 max-w-[560px] text-[10px] leading-6 text-bazooka-text-secondary sm:text-[11px]">Whether you want food, a drink, coffee or a quick refreshment, Cafe Bazooka gives you another stop inside the club. Menu items can change, so check the current selection when you visit.</p></motion.div><motion.div {...reveal} className="grid gap-3 sm:grid-cols-3">{benefits.map(([Icon,title,text])=><article key={title} className="rounded-[6px] border border-bazooka-border bg-bazooka-card p-5 transition-all duration-300 hover:-translate-y-1 hover:border-bazooka-lime"><div className="grid size-10 place-items-center rounded-full bg-bazooka-lime/10 text-bazooka-lime"><Icon className="size-5"/></div><h3 className="font-display mt-4 text-[16px] font-black uppercase">{title}</h3><p className="mt-3 text-[9px] leading-5 text-bazooka-text-secondary">{text}</p></article>)}</motion.div></div></section>

    <section id="menu" className="scroll-mt-24 border-b border-bazooka-border/70 bg-bazooka-black py-14 sm:py-16 md:py-20"><div className={shell}><motion.div {...reveal} className="max-w-[700px]"><span className="text-[9px] font-black uppercase tracking-[.12em] text-bazooka-lime">What You May Find</span><h2 className="font-display mt-3 text-[36px] font-black uppercase leading-[.9] min-[380px]:text-[40px] sm:text-[52px]">Food. Drinks.<br/>Refreshments.</h2><p className="mt-4 max-w-[560px] text-[10px] leading-5 text-bazooka-text-secondary">These categories describe the cafe experience rather than a fixed menu. Exact items and availability can vary.</p></motion.div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{categories.map(([Icon,title,text],index)=><motion.article key={title} {...reveal} transition={{duration:.5,delay:index*.05}} className="group rounded-[6px] border border-bazooka-border bg-bazooka-surface p-5 transition-all duration-300 hover:-translate-y-1 hover:border-bazooka-lime hover:bg-bazooka-card-hover sm:p-6"><Icon className="size-6 text-bazooka-lime transition-transform duration-300 group-hover:scale-110"/><h3 className="font-display mt-5 text-[19px] font-black uppercase">{title}</h3><p className="mt-3 text-[9px] leading-5 text-bazooka-text-secondary">{text}</p></motion.article>)}</div><div className="mt-5 rounded-[4px] border border-bazooka-border/70 bg-bazooka-surface/50 px-4 py-3 text-[8px] uppercase leading-4 tracking-[.06em] text-bazooka-muted">Menu availability may vary. Ask the Cafe Bazooka team for today’s options.</div></div></section>

    <section className="border-b border-bazooka-border/70 bg-bazooka-soft-black py-14 sm:py-16 md:py-20"><div className={shell}><motion.div {...reveal} className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><span className="text-[9px] font-black uppercase tracking-[.12em] text-bazooka-lime">The Cafe Space</span><h2 className="font-display mt-3 text-[36px] font-black uppercase leading-[.9] min-[380px]:text-[40px] sm:text-[52px]">Stop By During<br/>Your Visit.</h2></div><span className="max-w-[350px] text-[9px] leading-5 text-bazooka-text-secondary">A convenient extension of the Bazooka experience beyond the training floor.</span></motion.div><div className="mt-8 grid gap-4 md:grid-cols-[1.2fr_.8fr_.8fr]">{gallery.map((image,index)=><motion.div key={image} {...reveal} className={`overflow-hidden rounded-[6px] border border-bazooka-border bg-bazooka-card ${index===0?"min-h-[320px]":"min-h-[250px] md:min-h-[320px]"}`}><div className="h-full min-h-[inherit] bg-cover bg-center transition-transform duration-700 hover:scale-[1.035]" style={{backgroundImage:`url(${image})`}}/></motion.div>)}</div></div></section>

    <section className="border-b border-bazooka-border/70 bg-bazooka-black py-14 sm:py-16"><div className={`${shell} grid gap-4 md:grid-cols-2`}><motion.article {...reveal} className="rounded-[7px] border border-bazooka-border bg-bazooka-card p-6 sm:p-8"><Clock3 className="size-6 text-bazooka-lime"/><span className="mt-5 block text-[8px] font-black uppercase tracking-[.12em] text-bazooka-muted">Cafe Access</span><h3 className="font-display mt-2 text-[25px] font-black uppercase leading-none sm:text-[27px]">Check Today’s Availability.</h3><p className="mt-3 text-[10px] leading-5 text-bazooka-text-secondary">Ask the team at the club for current Cafe Bazooka operating hours and available items.</p></motion.article><motion.article {...reveal} className="rounded-[7px] border border-bazooka-border bg-bazooka-card p-6 sm:p-8"><MapPin className="size-6 text-bazooka-lime"/><span className="mt-5 block text-[8px] font-black uppercase tracking-[.12em] text-bazooka-muted">Location</span><h3 className="font-display mt-2 text-[25px] font-black uppercase leading-none sm:text-[27px]">Inside Bazooka Fitness.</h3><p className="mt-3 text-[10px] leading-5 text-bazooka-text-secondary">Floor 6, Shanti One, Plot No. 39, 11th A Road, Sardarpura, Jodhpur, Rajasthan 342001.</p></motion.article></div></section>

    <section className="border-b border-bazooka-border/70 bg-bazooka-black py-7"><div className={shell}><motion.div {...reveal} className="relative overflow-hidden rounded-[6px] border border-bazooka-border-strong"><div className="absolute inset-0 bg-[url('https://images.unsplash.com/photo-1543362906-acfc16c67564?auto=format&fit=crop&w=1600&q=90')] bg-cover bg-center"/><div className="absolute inset-0 bg-gradient-to-r from-black via-black/92 to-black/45"/><div className="relative z-10 grid min-h-[230px] gap-7 px-5 py-8 sm:px-7 lg:grid-cols-[1fr_auto] lg:items-center lg:px-8"><div><span className="text-[9px] font-black uppercase tracking-[.12em] text-bazooka-lime">Train • Visit • Recharge</span><h2 className="font-display mt-2 text-[30px] font-black uppercase leading-[.92] min-[380px]:text-[34px] sm:text-[42px]">Make Cafe Bazooka<br/><span className="text-bazooka-lime">Part Of Your Visit.</span></h2><p className="mt-3 max-w-[520px] text-[10px] leading-5 text-bazooka-text-secondary">Explore the cafe while you experience Bazooka Fitness for yourself.</p></div><div className="grid gap-3 sm:flex lg:grid"><Link href="/book-free-trial" className="inline-flex h-11 w-full items-center justify-center gap-3 rounded-[4px] border border-bazooka-lime bg-bazooka-lime px-6 text-[9px] font-black uppercase text-black transition hover:bg-bazooka-lime-hover active:scale-[.98] sm:w-auto">Book Free Trial <ArrowRight className="size-4"/></Link><Link href="/contact" className="inline-flex h-11 w-full items-center justify-center gap-3 rounded-[4px] border border-bazooka-border-strong bg-black/45 px-6 text-[9px] font-black uppercase text-white transition hover:border-bazooka-lime hover:text-bazooka-lime active:scale-[.98] sm:w-auto">Contact Bazooka</Link></div></div></motion.div></div></section>
  </main>;
}
