"use client";

import Link from "next/link";
import { AlertCircle, ArrowRight, Cookie, Copyright, CreditCard, Dumbbell, FileCheck2, FilePenLine, Gavel, Headphones, Info, Link2, LockKeyhole, Mail, Phone, Settings2, ShieldCheck, UserRound, UsersRound } from "lucide-react";

export type LegalKind = "privacy" | "terms" | "cookie" | "disclaimer";
type IconType = typeof UserRound;
type Card = { title: string; text: string; icon: IconType };
const shell = "mx-auto w-[min(calc(100%-32px),1180px)] sm:w-[min(calc(100%-40px),1180px)] md:w-[min(calc(100%-64px),1180px)]";
const heroImage = "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1800&q=90";
const button = "group inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-[4px] border border-bazooka-lime bg-bazooka-lime px-5 text-[9px] font-black uppercase text-black transition-all duration-300 hover:-translate-y-0.5 hover:bg-bazooka-lime-hover active:scale-[.97] sm:w-auto";

const privacyCards: Card[] = [
{icon:UserRound,title:"Information You Provide",text:"We may receive information you choose to provide through enquiries, trial requests, membership interactions or direct communication, such as your name, phone number, email address and message details."},
{icon:FileCheck2,title:"How Information Is Used",text:"Information may be used to respond to requests, provide requested services, administer memberships where applicable, communicate with you and operate the business."},
{icon:Link2,title:"Service Providers",text:"Where external providers are used for hosting, communications, payments or other operations, information may be processed by those providers subject to their applicable terms and safeguards."},
{icon:LockKeyhole,title:"Security",text:"Reasonable steps may be used to protect information handled by Bazooka Fitness, but no website, transmission method or storage system can be guaranteed to be completely secure."},
{icon:Cookie,title:"Cookies & Similar Technology",text:"The website may use cookies or similar browser technologies required for functionality or introduced by services integrated into the site. Your browser can provide controls for stored cookies."},
{icon:Settings2,title:"Requests & Preferences",text:"You can contact Bazooka Fitness about personal information you previously provided or communication preferences. Requests are handled subject to applicable law and operational requirements."},
{icon:FilePenLine,title:"Retention & Updates",text:"Information may be retained for as long as reasonably required for its purpose, operational needs or legal obligations. This policy may be updated as the website and services change."},
{icon:Mail,title:"Privacy Contact",text:"For questions about this policy or information you have provided, contact Bazooka Fitness using the published phone number, email address or Contact page."},
];
const termsCards: Card[] = [
{icon:UserRound,title:"Membership",text:"Membership access and use are subject to the plan purchased, the membership terms accepted at joining and the current rules communicated by Bazooka Fitness."},
{icon:CreditCard,title:"Pricing & Payments",text:"Website prices and plan information should be confirmed before payment. Refund, cancellation, transfer, freeze and upgrade eligibility depend on the applicable plan and policies."},
{icon:Dumbbell,title:"Facility Use",text:"Members and visitors should use equipment responsibly, follow staff instructions and comply with safety, hygiene and conduct requirements communicated at the club."},
{icon:ShieldCheck,title:"Health & Exercise",text:"Exercise involves physical effort and individual circumstances differ. Seek appropriate professional medical advice before starting or changing exercise where your health or circumstances require it."},
{icon:UsersRound,title:"Conduct",text:"Respectful behaviour toward staff, members and visitors is expected. Access may be restricted where conduct creates safety, security or operational concerns, subject to applicable terms and law."},
{icon:LockKeyhole,title:"Personal Belongings",text:"Take reasonable care of personal belongings while at the facility and follow any locker or storage rules communicated by the club."},
{icon:Info,title:"Photography & Recording",text:"Photography and recording should respect other members, staff, privacy and any instructions or restrictions communicated by Bazooka Fitness at the facility."},
{icon:FilePenLine,title:"Changes",text:"Website information, facilities, schedules, pricing and these terms may be updated. Material terms applicable to an existing purchase remain subject to the agreement and law governing that purchase."},
{icon:Gavel,title:"Applicable Law",text:"These terms are intended to operate subject to applicable Indian law. Nothing on this page is intended to remove rights or obligations that cannot legally be excluded."},
];
const cookieCards: Card[] = [
{icon:Cookie,title:"What Cookies Are",text:"Cookies are small pieces of data a website or connected service can store in your browser to support functionality, preferences, security or measurement."},
{icon:ShieldCheck,title:"Essential Technology",text:"Some browser storage may be necessary for website functionality or security. Disabling it can affect how parts of a website work."},
{icon:Settings2,title:"Your Browser Controls",text:"You can review, block or remove cookies through your browser settings. The exact controls depend on the browser and device you use."},
{icon:Link2,title:"Third-Party Services",text:"Embedded or linked third-party services may use their own cookies or similar technologies. Their handling is governed by their own policies and settings."},
{icon:FilePenLine,title:"Changes To Cookie Use",text:"Cookie usage can change when website features, analytics, embeds or other integrations are added or removed. This page may be updated accordingly."},
{icon:Mail,title:"Questions",text:"If you have a question about technologies used on the Bazooka Fitness website, contact the team using the details published on the Contact page."},
];
const disclaimerCards: Card[] = [
{icon:Info,title:"General Information",text:"Website content is provided for general information about Bazooka Fitness, its facilities, programs and services. It should not be treated as individualized professional advice."},
{icon:UserRound,title:"Fitness & Health Information",text:"Fitness, training or nutrition-related content is not a substitute for medical diagnosis, treatment or advice from an appropriately qualified professional."},
{icon:FileCheck2,title:"Individual Results",text:"Training outcomes differ between individuals and depend on many factors. No specific body-composition, strength, weight or fitness result is guaranteed by the website."},
{icon:Dumbbell,title:"Participation",text:"Use equipment and participate in exercise according to your circumstances, staff guidance and applicable membership or facility rules."},
{icon:Link2,title:"External Content",text:"Links or integrations can lead to services operated by third parties. Bazooka Fitness does not control the availability, terms, privacy practices or content of those independent services."},
{icon:Copyright,title:"Site Content",text:"Brand assets and original website content may be protected by intellectual-property rights. Third-party imagery, icons, software and other materials remain subject to their respective licences and rights."},
{icon:CreditCard,title:"Plans, Prices & Availability",text:"Membership details, prices, facilities, schedules and service availability can change. Confirm information important to a purchase or visit directly with the Bazooka team."},
{icon:FilePenLine,title:"Website Updates",text:"Bazooka Fitness may correct, replace or update website information as the business and services change. If website content conflicts with a specific accepted agreement, review the applicable agreement."},
];
const content={
privacy:{crumb:"Privacy Policy",title:"Privacy",accent:"Policy",intro:"A clear overview of how information provided through the Bazooka Fitness website and business interactions may be handled.",cards:privacyCards,note:"This page describes the website’s current general privacy approach. Specific third-party services and operational processes may have additional terms or privacy notices."},
terms:{crumb:"Terms & Conditions",title:"Terms &",accent:"Conditions",intro:"General website and facility terms designed to sit alongside the specific membership or service agreement applicable to your purchase.",cards:termsCards,note:"Plan-specific membership, cancellation, refund and freeze terms should be confirmed before purchase. A specific agreement accepted for a transaction can contain additional terms."},
cookie:{crumb:"Cookie Policy",title:"Cookie",accent:"Policy",intro:"An overview of cookies and similar browser technologies that may be used by this website or connected services.",cards:cookieCards,note:"This page does not claim that every category of cookie is currently active. Browser storage and third-party technologies depend on the features and services actually enabled on the website."},
disclaimer:{crumb:"Disclaimer",title:"Website",accent:"Disclaimer",intro:"Important context about fitness information, results, external services and website content published by Bazooka Fitness.",cards:disclaimerCards,note:"Nothing on this page is intended to exclude responsibilities or consumer rights that cannot be excluded under applicable law."},
} satisfies Record<LegalKind,{crumb:string;title:string;accent:string;intro:string;cards:Card[];note:string}>;

export default function LegalPage({kind}:{kind:LegalKind}){const page=content[kind];return <main className="min-h-screen overflow-x-hidden bg-bazooka-black text-bazooka-text"><Hero crumb={page.crumb} title={page.title} accent={page.accent} intro={page.intro}/><section className="border-b border-bazooka-border/70 bg-bazooka-black py-12 sm:py-14 md:py-16"><div className={shell}><div className="max-w-[720px]"><span className="text-[9px] font-black uppercase tracking-[.12em] text-bazooka-lime">Bazooka Fitness</span><h2 className="font-display mt-2 text-[32px] font-black uppercase leading-[.95] sm:text-[42px]">Understand The <span className="text-bazooka-lime">Details.</span></h2><p className="mt-3 text-[10px] leading-5 text-bazooka-text-secondary">Read the sections below together with any membership or service-specific terms provided when you join, purchase or book.</p></div><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{page.cards.map((card,index)=><LegalCard key={card.title} card={card} index={index}/>)}</div><div className="mt-4 flex gap-4 rounded-[6px] border border-bazooka-lime/50 bg-bazooka-surface p-5 sm:p-6"><AlertCircle className="mt-0.5 size-6 shrink-0 text-bazooka-lime"/><div><strong className="font-display text-[16px] uppercase text-bazooka-lime">Important Context</strong><p className="mt-2 max-w-[900px] text-[9px] leading-5 text-bazooka-text-secondary">{page.note}</p></div></div><HelpStrip/></div></section></main>}
function Hero({crumb,title,accent,intro}:{crumb:string;title:string;accent:string;intro:string}){return <section className="relative min-h-[430px] overflow-hidden border-b border-bazooka-border/70 bg-cover bg-center sm:min-h-[470px]" style={{backgroundImage:`url(${heroImage})`}}><div className="absolute inset-0 bg-gradient-to-r from-black via-black/84 to-black/20"/><div className="absolute inset-0 bg-gradient-to-t from-black/45 via-transparent to-black/20"/><div className={`${shell} relative z-10 flex min-h-[430px] items-center py-28 sm:min-h-[470px]`}><div className="max-w-[650px]"><p className="flex flex-wrap items-center gap-2 text-[9px] text-bazooka-text-secondary"><Link href="/" className="transition hover:text-bazooka-lime">Home</Link><span className="text-bazooka-lime">›</span><span>{crumb}</span></p><h1 className="font-display mt-6 max-w-full text-[44px] font-black uppercase leading-[.88] min-[380px]:text-[50px] sm:text-[68px]">{title}<br/><span className="text-bazooka-lime">{accent}</span></h1><span className="mt-6 block h-0.5 w-10 bg-bazooka-lime"/><p className="mt-5 max-w-[540px] text-[11px] leading-6 text-bazooka-text-secondary sm:text-[12px]">{intro}</p></div></div></section>}
function LegalCard({card,index}:{card:Card;index:number}){const Icon=card.icon;return <article className="group min-h-[230px] rounded-[6px] border border-bazooka-border-strong bg-bazooka-surface p-5 transition-all duration-300 hover:-translate-y-1 hover:border-bazooka-lime/70 sm:p-6"><div className="flex items-center justify-between gap-4"><span className="grid size-11 place-items-center rounded-full border border-bazooka-lime/25 bg-bazooka-lime/5 text-bazooka-lime transition group-hover:border-bazooka-lime group-hover:bg-bazooka-lime group-hover:text-black"><Icon className="size-5"/></span><span className="font-display text-[16px] font-black text-bazooka-lime">{String(index+1).padStart(2,"0")}</span></div><h3 className="font-display mt-5 text-[17px] font-black uppercase leading-5">{card.title}</h3><p className="mt-3 text-[9px] leading-5 text-bazooka-text-secondary">{card.text}</p></article>}
function HelpStrip(){return <div className="mt-4 grid gap-5 rounded-[6px] border border-bazooka-border-strong bg-bazooka-surface p-5 sm:p-6 lg:grid-cols-[1fr_auto_auto_auto] lg:items-center"><div className="flex gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-full border border-bazooka-lime/40 bg-bazooka-lime/5 text-bazooka-lime"><Headphones className="size-5"/></span><div><h2 className="font-display text-[21px] font-black uppercase">Questions About A Policy?</h2><p className="mt-1 max-w-[380px] text-[9px] leading-4 text-bazooka-text-secondary">Contact the Bazooka team if a policy affects a membership, payment or visit you are considering.</p></div></div><div className="border-t border-bazooka-border pt-4 text-[9px] lg:border-l lg:border-t-0 lg:pl-5 lg:pt-0"><Phone className="size-4 text-bazooka-lime"/><strong className="mt-2 block">+91 91164 05151</strong></div><div className="border-t border-bazooka-border pt-4 text-[9px] lg:border-l lg:border-t-0 lg:pl-5 lg:pt-0"><Mail className="size-4 text-bazooka-lime"/><strong className="mt-2 block">store@bazooka.fit</strong></div><Link href="/contact" className={button}>Contact Us <ArrowRight className="size-4 transition-transform group-hover:translate-x-1"/></Link></div>}
